### PR TITLE
gracefully restart

### PR DESCRIPTION
**Pull request by mazubieta**
related to this issue: https://github.com/concourse/concourse/issues/1251

This will:
1. ensure a worker retires itself anytime the service is stopped.
2. on start up, ensure that the TSA doesn't have stale information on this worker

### CODE REVIEW

**Comment by ahelal** [comment]
@mazubieta thank you for the PR. While that make sense, I would suggest to change the retire script. At the moment it will loop forever.

I am not sure about the approach:
1. if we can check if worker is registered then we can skip retiring. Or maybe the exit code gives us hints.
2. We attempt 5 times and fails after that.

What is your thoughts ?

**Comment by mazubieta** [comment]
> if we can check if worker is registered then we can skip retiring. Or maybe the exit code gives us hints.

The script is already attempting to check if the worker is registered:
https://github.com/ahelal/ansible-concourse/blob/master/templates/concourse-worker-retire.j2#L18-L19
> We attempt 5 times and fails after that.
This is a good addition, I'll give this a shot and include it in this PR.

I believe there is one issue, albeit one that only arises if the user has some less-than-ideal naming structure.
The scenario is this:
_If a user of this role has workers whose name is a subset of another worker's name_

example:
Worker 1 name: `ci_worker`
Worker 2 name: `ci_worker2`

In this example the issue would arise when attempting to retire `ci_worker`, because `{{ concourseci_bin_dir }}/fly -t manage workers | grep ${CONCOURSE_NAME}` will always find `ci_worker`, because of `ci_worker2`

I can see if I can adjust the check to account for this, as well.

**Comment by mazubieta** [comment]
@ahelal please see my additions above

**Comment by mazubieta** [comment]
Thanks for the feedback.  I've made the requested changes.  I'll be interested to understand your issues concerning the init script.

**Comment by ahelal** [comment]
Thank you, will merge it now and give it a test. I will not release a new version till i verify that the retire is working.

Concerning the init script. the formatting will be broken since and since we print multiline it will look ugly, But I can fix that after testing.

**Comment by mazubieta** [comment]
Sounds good.  I'm in the concourse slack as `zubnola` if you want/need to
chat about this in a more realtime manner.

**Pull request merged**
